env:
  PUBLISH_SOURCES: 'true'
jobs:
  bazel:
    name: Bazel
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-bazel-${{ github.sha }}
        path: ~/.cache/bazel
        restore-keys: '${{ runner.os }}-bazel-

          '
    - continue-on-error: true
      name: Info
      run: bazel --bazelrc=.ci.bazelrc info release
    - continue-on-error: true
      name: Unit Tests
      run: bazel --bazelrc=.ci.bazelrc test //jflex/...
    - continue-on-error: true
      name: Integration+Regression Tests
      run: bazel --bazelrc=.ci.bazelrc test //javatests/...
    - continue-on-error: true
      name: Build all
      run: bazel --bazelrc=.ci.bazelrc build //...
    - continue-on-error: true
      name: Test all
      run: bazel --bazelrc=.ci.bazelrc test //...
    - continue-on-error: true
      name: Build artifact
      run: bazel --bazelrc=.ci.bazelrc build jflex/jflex_bin_deploy.jar
    - continue-on-error: true
      name: Check aggregated sources
      run: 'bazel --bazelrc=.ci.bazelrc build //jflex:jflex_bin_deploy-src.jar //jflex:resources

        mkdir -p jflex_bin_deploy; cd jflex_bin_deploy

        cp ../scripts/compile-aggregated-java-sources.sh compile.sh

        jar -xf ../bazel-bin/jflex/jflex_bin_deploy-src.jar

        jar -xf ../bazel-bin/jflex/libresources.jar

        ./compile.sh

        ls jflex/Main.class

        '
  build:
    name: Maven & Examples
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: "\U0001F528 Maven (build, test)"
      run: scripts/test-unit.sh
    - continue-on-error: true
      name: "\U0001F528 Maven (site)"
      run: scripts/mvn-site.sh
    - continue-on-error: true
      name: "\U0001F528 Maven (aggregate sources)"
      run: scripts/mvn-aggregate-srcs.sh
    - continue-on-error: true
      name: "\U0001F60E Examples (mvn, ant, make)"
      run: scripts/test-examples.sh
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        os:
        - ubuntu-latest
        - macos-latest
  docs:
    name: Docs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install LaTeX and pandoc
      run: "sudo apt-get install \\\n     pandoc pandoc-citeproc texlive texlive-latex-extra\
        \ lmodern\n"
    - continue-on-error: true
      name: "\U0001F4C4 Documentation"
      run: cd docs; make
  javadoc:
    name: Javadoc
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: "\U0001F528 Build JFlex jar"
      run: 'mvn -Pfastbuild install

        '
    - continue-on-error: true
      name: "\U0001F4DD Javadoc"
      run: 'mvn javadoc:javadoc

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
  regression:
    name: Regression
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: "\U0001F4DD Regression tests"
      run: 'scripts/mvn-install-fastbuild.sh jflex-maven-plugin,testsuite/jflex-testsuite-maven-plugin

        scripts/test-regression.sh

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        os:
        - ubuntu-latest
        - macos-latest
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
