env:
  PUBLISH_SOURCES: 'true'
jobs:
  deploy:
    name: Sources
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        path: jflex
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        path: aggregated-java-sources
        ref: aggregated-java-sources
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-bazel-${{ github.sha }}
        path: ~/.cache/bazel
        restore-keys: '${{ runner.os }}-bazel-

          '
    - continue-on-error: true
      name: Info
      run: cd jflex; bazel --bazelrc=.ci.bazelrc info release
    - continue-on-error: true
      name: Prepare aggregated sources
      run: 'cd jflex; scripts/prepare-deploy-source-code.sh

        '
    - continue-on-error: true
      name: Push
      run: 'cd aggregated-java-sources; git push

        '
name: Deploy Sources
on:
  repository_dispatch:
    types: trigger-ga___deploy-src.yml
