jobs:
  check:
    name: License
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check
      uses: fsfe/reuse-action@v1
name: License Check
on:
  repository_dispatch:
    types: trigger-ga___license.yml
